= Tech Assessment - Harver - Cat Card Application
Author : Amila Samaranayake
:description: Project Cat_Card_Application is a simple application to fetches two images with some custom texts and blended together into one image called cat-card image.
:keywords: NodeJs, Typescript, MongoDB, Docker, RestAPI, HTML, Javascript, Bootstrap
:page-description: {description}
:page-keywords: {keywords}
:page-layout: docs
ifndef::env-site[]
:toc: left
:icons: font
:idprefix:
:idseparator: -
:sectanchors:
:source-highlighter: highlightjs
endif::[]
:experimental:
:mdash: &#8212;
:language: asciidoc
:source-language: {language}
:table-caption!:
:example-caption!:
:figure-caption!:
:imagesdir: ./images
// Refs
:url-github: https://github.com/JohnzCooper/Cat_Card_Application.git

Project Cat_Card_Application is a simple application to fetches two images with some custom texts and blended together into one image called cat-card image. + 

TIP: You can find the Github repo in {url-github}[Cat_Card_Application].

In this document:

- The introduction
- Prerequisite and local installation guide
- Application run and test guide
- Describe assumption and dependencies

Let's dive in to Cat_Card_Application!

== Introduction 

This is a simple application to fetches two images with some custom texts and blended together into one image called cat-card image. 

== Prerequisite and local installation guide

Primary requirements for the project are Node installed on your environment.

TIP: Open up a terminal and run following commands to check primary requirements  + 
`node -v` : If Node installed you will get the Node version  + 

1. Download or clone source code from github {url-github}[https://github.com/JohnzCooper/Cat_Card_Application.git]
2. Open the source via a code editor or cmd
3. Run `npm install`
4. Run `node app --greeting your-text --who your-text` +

== Application run and test guide

This application need to pass the texts as *command line arguments*. + 
--
----
node app --greeting first-text --who second-text --width custom-width --height custom-height --color custom-color --size custom-size
----
--
=== Available Options as command line arguments

* greeting: + 
    First image text argument.

* who: + 
    Second image text argument.

* Image Options: + 
** width: + 
    Custom image width

** height: + 
    Custom image height

** color: +
    Custom text color
    
** size: + 
    Custom image size


== Describe assumption and dependencies

* Assume this application is to save single cat-card image in `/image` folder and update same cat-card image in next run. 

== Documentation

* The document is in `asciidoc` format and It is in the repo.(`/docs` directory).

